# Site settings
title: Your awesome title
email: your-email@domain.com
author: your name
project_name: project
project_site: http://mysite.com
download_url: http://mysite.com/download
short_description: >
  <p>Free Bootstrap theme for your project documentation</p>
  <p>Designed with <i class="fa fa-heart"></i> for developers</p>
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: TWITTER_USER
github_username:  GITHUB_USER


markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      body_color: "orange"
      layout: "page"
      title_icon: fa fa-link

# allowed colors: green, blue, orange, red, pink, purple
